### ISSUE TITLE
CI testing failing

### ISSUE THREAD

**Issue by jiaola** [projectblacklight/blacklight_folders#99]
Hi, 

I can't get the rspec to work. Below are the errors. There are also pull requests with similar errors. See pull request #97 and #98 on travis: https://travis-ci.org/projectblacklight/blacklight_folders/pull_requests

        Migrations are pending. To resolve this issue, run:

	bin/rake db:migrate RAILS_ENV=test

	from /Users/djiao/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:406:in `load_schema_if_pending!'
	from /Users/djiao/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:412:in `block in maintain_test_schema!'
	from /Users/djiao/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:640:in `suppress_messages'
	from /Users/djiao/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:417:in `method_missing'
	from /Users/djiao/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.1/lib/active_record/migration.rb:412:in `maintain_test_schema!'
	from /Users/djiao/Projects/RubyMineProjects/blacklight_folders/spec/rails_helper.rb:36:in `<top (required)>'
	from /Users/djiao/Projects/RubyMineProjects/blacklight_folders/spec/controllers/blacklight/folders/folders_controller_spec.rb:1:in `require'
	from /Users/djiao/Projects/RubyMineProjects/blacklight_folders/spec/controllers/blacklight/folders/folders_controller_spec.rb:1:in `<top (required)>'
	from /Users/djiao/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.2.3/lib/rspec/core/configuration.rb:1226:in `load'
	from /Users/djiao/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.2.3/lib/rspec/core/configuration.rb:1226:in `block in load_spec_files'
	from /Users/djiao/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.2.3/lib/rspec/core/configuration.rb:1224:in `each'
	from /Users/djiao/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.2.3/lib/rspec/core/configuration.rb:1224:in `load_spec_files'
	from /Users/djiao/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:97:in `setup'
	from /Users/djiao/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:85:in `run'
	from /Users/djiao/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:70:in `run'
	from /Users/djiao/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:38:in `invoke'
	from /Users/djiao/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.2.3/exe/rspec:4:in `<main>'
        /Users/djiao/.rvm/rubies/ruby-2.1.5/bin/ruby -I/Users/djiao/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.2.3/lib:/Users/djiao/.rvm/gems/ruby-2.1.5/gems/rspec-support-3.2.2/lib /Users/djiao/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.2.3/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb failed

**Comment by cjcolvar** [comment]
It looks like @jcoyne started work on this in this branch: https://github.com/projectblacklight/blacklight_folders/tree/no_migration

**Comment by jcoyne** [comment]
Fixed by #101
